name: flowers0
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_yookassa:
  #  path: /Users/pavel/Desktop/Projects/Flutter-Yookassa-Package
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.1 
  firebase_database: ^6.0.0
  cloud_firestore: ^1.0.3
  provider: ^4.3.3
  firebase_core: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  cupertino_icons: ^1.0.0
  firebase_image: ^1.0.1
  get: ^4.1.4
  firebase_messaging: ^10.0.8
  pull_to_refresh: ^2.0.0
  flutter_local_notifications: ^9.0.1
  credit_card_type_detector: ^1.0.2
  uuid: ^3.0.4
  hex: ^0.2.0
  flutter_swiper: ^1.1.6
  top_snackbar_flutter: ^1.0.0
  expandable: ^5.0.1
  skeleton_loader: ^2.0.0+4
  fluttertoast: ^8.0.8
  vertical_tab_bar_view: ^0.0.1
  flutter_vibrate: ^1.3.0
  scrollable_list_tab_scroller: ^0.1.0
  easy_debounce: ^2.0.1
  octo_image: ^1.0.0+1
  connectivity: ^3.0.6
  url_launcher: ^6.0.4


  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - lib/assets/
 

